version: '3'

services:
  loadbalancer:
    image: golang:1.22.3-alpine
    working_dir: /app/lb
    volumes:
      - ./lb:/app/lb
    command: sh -c "cd /app/lb && go build -o lb . && ./lb"
    ports:
      - "80:80"
    depends_on:
      - backend1
      - backend2

  backend1:
    image: golang:1.22.3-alpine
    working_dir: /app/be1
    volumes:
      - ./be1:/app/be1
    command: sh -c "cd /app/be1 && go build -o be1 . && ./be1"
    ports:
      - "5433:5433"
  
  backend2:
    image: golang:1.22.3-alpine
    working_dir: /app/be2
    volumes:
      - ./be2:/app/be2
    command: sh -c "cd /app/be2 && go build -o be2 . && ./be2"
    ports:
      - "5434:5434"
